### ISSUE TITLE
Kodi 21 not supported

### ISSUE THREAD

**Issue by wvanderwees** [ziggotv/ziggotv.github.io#2]
This Ziggo app is working perfect at Kodi 20 but at the new Kodi 21 it won't play.

**Comment by tgiesela** [comment]
Just upgraded my own Kodi 20 installation on Windows 11 to the new Kodi 21 and I don't see any problems so far. So can you please explain how you upgraded, on which OS you are running Kodi and provide a debug log for further investigation?

**Comment by wvanderwees** [comment]
I installed Kodi 21 on Windows-10, on a Raspberry Pi 4 and on a Raspberry Pi 3B(a fresh clean install a few minutes ago).
[kodi.log](https://github.com/ziggotv/ziggotv.github.io/files/14999703/kodi.log)
All these computers were running Kodi 20 and your Ziggo-app before without any problems.

**Comment by wvanderwees** [comment]
I installed Kodi 21 on Windows-10, on a Raspberry Pi 4 and on a Raspberry Pi 3B(a fresh clean install a few minutes ago).
All these computers were running Kodi 20 and your Ziggo-app before without any problems.
[kodi.log](https://github.com/ziggotv/ziggotv.github.io/files/14999776/kodi.log)
I accidently closed this issue.

**Comment by tgiesela** [comment]
Fixed the problem. The log showed it was a problem with the missing the widevine.so library. It was caused by a missing check on InputStream Adaptive when playing channels or recordings. EPG should have played fine.

**Comment by wvanderwees** [comment]
Just updated the Ziggo app to 1.01 and updated widevine on Windows-10 and Raspberry Pi 3B but it still won't play.
[kodi.log](https://github.com/ziggotv/ziggotv.github.io/files/15025136/kodi.log)

**Comment by tgiesela** [comment]
On my Windows-11 installation I have no issues at all. I just started with Libreelec on a RPI 4 and now I have to install InputStream Adaptive manually (on windows it is automatic). In the log you see the following messages:

> 2024-04-18 14:51:58.581 T:878     error <general>: AddOnLog: inputstream.adaptive: Write: Cannot create directory: /storage/.kodi/userdata/addon_data/inputstream.adaptive/widevine/5c016e8f0f95f039102cbe8366c5c7f3/

So a folder that should be there is missing. For now I created the folder /storage/.kodi/userdata/addon_data/inputstream.adaptive/widevine/5c016e8f0f95f039102cbe8366c5c7f3/ myself and then it is working.

I will do some further investigation why the folder is not created. But that is not done by my plugin, it something within InputstreamAdaptive or InputstreamHelper which are not created by me.

**Comment by tgiesela** [comment]
You (and I) were using a Beta version of LibreElec. If you go back to the stable version you will not have this problem. I checked the version of ISA (InputStreamAdaptive) and they are different:

> LibreElec stable (2024.01, LibreELEC 11.0)
> 	inputstream.adaptive **v20.3.18.1** => OK
> 	
> LibreElec beta (2024.04, LibreELEC 12.0)
> 	inputstream.adaptive **v21.4.5.1** => inputstream.adaptive: Write: Cannot create directory: /storage/.kodi/userdata/addon_data/inputstream.adaptive/widevine/5c016e8f0f95f039102cbe8366c5c7f3/
> 	
> Windows 11
> 	inputstream.adaptive **v21.4.5**	=> OK
> 

My assumption is that there is still some development ongoing for the Beta version.

**Comment by wvanderwees** [comment]
Thanks for your solution!, I don't think the problem is the libreelec version because I have the same problem under Windows-10 and my new Raspberry Pi 5 with Raspberry Pi OS and Kodi 21.

**Comment by tgiesela** [comment]
Well maybe I should rephrase it. It is probably the ISA version (**v21.4.5.1**) used by Libreelec Beta, which causes the issue. I do not have a windows 10 installation, so I can't test that. As stated before: in Windows 11 Kodi 21.0 works fine (not LibreElec of course). See the versions of ISA on my test-systems. 
Anyway, I created a bug report for LibreElec because I think they created a new version of ISA which causes the problem. The stable versions work fine.

**Comment by wvanderwees** [comment]
The workaround works fine for me. B.t.w. I just also installed Kodi 12 on my other Windows-11 laptop and have the same problem as my other pc's. But anyway thanks for all your good work!

**Comment by tgiesela** [comment]
That is strange, because mine is working fine with a fresh Install of kodi 12. If you send me the log and the exact version of Kodi I will check again to see what the problem is.

**Comment by wvanderwees** [comment]
I will sent it tomorrow.

**Comment by wvanderwees** [comment]
I removed Kodi 12 from my Windows-11 laptop and re-installed it after a reboot and your fantastic Ziggo app is working without a problem now without the workaround.
