### ISSUE TITLE
Directoy missing for Widevine key (inputstream.adaptive: Write: Cannot create directory)

### ISSUE THREAD

**Issue by jeroenhabets** [ziggotv/ziggotv.github.io#3]
(Not sure if I am barking up the right tree here but as I found a workaround it may be useful to a fellow ZiggoTV add-on user)

After switching Kodi to flatpak and reinstalling this ZiggoTV add-on I could not watch any live tv getting the following error in my kodi.log:

```
AddOnLog: inputstream.adaptive: Write: Cannot create directory: /home/kodi/.var/app/tv.kodi.Kodi/data/userdata/addon_data/inputstream.adaptive/widevine/5c016e8f0f95f039102cbe8366c5c7f3/
```

## Workaround
After manually creating the mentioned subdirectories under `userdata/addon_data`, e.g. `inputstream.adaptive/widevine/5c016e8f0f95f039102cbe8366c5c7f3/`

```
cd /home/kodi/.var/app/tv.kodi.Kodi/data/userdata/addon_data
mkdir inputstream.adaptive
mkdir inputstream.adaptive/widevine
mkdir inputstream.adaptive/widevine/5c016e8f0f95f039102cbe8366c5c7f3
```

it worked like a breeze.

Kodi (21.0 (21.0.0) Git:20240406-60c4500-dirty)
plugin.video.ziggotv v1.0.4
inputstream.adaptive v21.4.4

**Comment by tgiesela** [comment]
Thanks for posting the workaround here. 
It was discvovered on a Beta version of LibreElec(2024.04), but I think you are running Kodi 21.0 on a different platform?

**Comment by jeroenhabets** [comment]
Sorry, I have missed your question: yes, I am running Ubuntu 22.04.5 LTS (using ALSA for pass-through HDMI audio)
