### ISSUE TITLE
Library version

### ISSUE THREAD

**Issue by JxxIT** [ziggotv/ziggotv.github.io#6]
Hi,

Thanks for this addon!
Is there a lib version of this, so I can authenticate and get proxy urls to stream directly? If there isn't, can you give me a few hints on how to do so?

Thanks!

**Comment by JxxIT** [comment]
CC @tgiesela

**Comment by tgiesela** [comment]
Sorry, I missed your original question. 
No, there is not a lib version. 
I am not sure if I understand what you are trying to achieve. As far as I know, all streams are DRM protected. This means you can only stream them via InputStream Adaptive or a Widevine certified library. 
You can however send requests to the proxy to authenticate and obtain the list of channels:

authenticate: curl -iv http://127.0.0.1:6969/function/LoginSession.login?args=%7B%22username%22%3A%22<username>%22%2C%22password%22%3A%22<password>%22%7D
channels: curl -iv http://127.0.0.1:6969/function/LoginSession.get_channels?args=%7B%7D

Note: you will receive output encoded using pythons pickle library.

For more info on other functions, you will have to enable debug mode and check the log.

**Comment by JxxIT** [comment]
@tgiesela Thanks for your reply!

I wanted to use this in my python project, to authenticate and fetch the channels. Now at least know where to look, thanks!
